### ISSUE TITLE
Question: Handling nodeosd forks

### ISSUE THREAD

**Issue by jcalfee** [eosrio/Hyperion-History-API#11]
Could you please give me a quick over-view on how you handle nodeosd forks?  I would like to look at how you handle this in your code..

I see `workers/state-reader.worker.js` is calling `requestBlockRange(msg.data.first_block, msg.data.last_block)` from nodeosd via `get_blocks_request_v0` with `irreversible_only` set to false.  How do you recover if you see a block that disappears due to a fork?

**Comment by igorls** [comment]
Blocks are indexed on elasticsearch by block_num and actions by global sequence, so after a fork happens the correct actions override the forked ones

**Comment by jcalfee** [comment]
Interesting .. So the global action sequence values from block one to the head block never skip any values.  Is that your understanding?

**Comment by igorls** [comment]
> Interesting .. So the global action sequence values from block one to the head block never skip any values. Is that your understanding?

yes, as far as I know the normal behavior would be not to skip, am I wrong ?

**Comment by jcalfee** [comment]
Not sure for EOS .. Unusual for a database though where a transaction got rolled back.  They don't re-use sequence numbers even for a rollback.  However, this is a very good idea on how to deal with forks.  I would not be surprised if this is correct.  I'll look this, this as least gives me a place to look.

I'm going to be busy on something else all next week.  Feel free to close the issue if you want.  I'll come back and update this when I find out.

**Comment by tbfleming** [comment]
sequence numbers roll back on forks.
