### ISSUE TITLE
Does Hyperion support Leap 3.1?

### ISSUE THREAD

**Issue by 1921Aaron** [eosrio/hyperion-history-api#120]

**Comment by igorls** [comment]
Yes, leap 3.1 is supported under the parser 1.8 for now. A fully dedicated version for leap will be published soon

**Comment by jun0tpyrc** [comment]
waiting for this one ,

hitting
```
type "get_blocks_request_v1" is not valid for variant
```
on 2.1/1.8 parser  on v3.3.4-rc8
