### ISSUE TITLE
How to enable trace history api?

### ISSUE THREAD

**Issue by YuXiaoCoder** [eosrio/hyperion-history-api#128]
I can get relevant trace information from the block explorer, but not from my own nodes
https://bloks.io/transaction/1269543cd1c17c9fa28493cc5d8b363bba7aa969c8c98700187a889a8bac594c?tab=raw
<img width="1148" alt="image" src="https://user-images.githubusercontent.com/26297513/201835898-6a9e7ce8-1864-4b91-b4e6-0ded278dd2fb.png">

**Comment by igorls** [comment]
please reopen if relevant on the latest version and include more information on the issue
