### ISSUE TITLE
support POST request for get_key_accounts

### ISSUE THREAD

**Issue by robertkowalski** [eosrio/Hyperion-History-API#13]
Hi folks,

when using scatter 11, it requires the old history api running with an eos node: https://github.com/GetScatter/ScatterDesktop/issues/410#issuecomment-507715933 to make a request to `get_key_accounts`

currently hyperion’s `get_key_accounts` uses GET- while the original history API works with POST.

on a load balancer level, rewriting the POST request to a GET becomes messy and requires some custom scripting, given the LB supports custom scripts.

with a custom proxy, e.g. written in nodejs, more moving parts are added to the infrastructure, which require maintanance in the long term. 

would you merge a PR to support the POST route additionally to the current GET request?

I could prepare a patch tomorrow. let me know what you think.

**Comment by igorls** [comment]
working on it already, thanks for the suggestion ;)

**Comment by igorls** [comment]
This commit implements it: https://github.com/eosrio/Hyperion-History-API/commit/a04fdc8de4e5df023dbb454a615facf5d4131e3b

**Comment by nsjames** [comment]
So this aligns with the old standard then? No changes on our end?

**Comment by robertkowalski** [comment]
yep! :)
