### ISSUE TITLE
pathComponents.at is not a function

### ISSUE THREAD

**Issue by luoxiandong** [eosrio/hyperion-history-api#132]
I request v1 compatible found some error:
`curl --header 'Content-type: application/json' -X POST "http://127.0.0.1:7000/v1/chain/get_block" -d '{"block_num_or_id": "281400906"}'`
display:
`{
statusCode: 500,
error: "Internal Server Error",
message: "pathComponents.at is not a function"
}`
How to solve？

**Comment by igorls** [comment]
This is solved by running on Node.js v18

**Comment by YudaAdiPratama** [comment]
@igorls pathComponents.at is not a function use nodejs v20
