### ISSUE TITLE
Our Hyperion Fork is Not Pulling From Our Docker Image

### ISSUE THREAD

**Issue by siliconswampio** [eosrio/hyperion-history-api#135]
We forked the Hyperion repo and made some changes to get it to work with our blockchain. We created a new Docker image, but whenever we run Docker, our changes are not being reflected. For example, we want it to pull our ABI repo, but it keeps pulling from the default one.

**Comment by igorls** [comment]
please reopen if relevant on the latest version and include more information on the issue
