### ISSUE TITLE
filter actions instead of whole trace

### ISSUE THREAD

**Issue by dev-dantealighieri** [eosrio/hyperion-history-api#144]
i want to get only the actions created by the creator of the transaction but history api returns whole transaction to me, 

im using the following code snippet to get the transaction
```typescript
const transaction = await this.indexerRequest(
      EOS_INDEXER_API.V2.GET_TRANSACTION,
      {
        params: {
          id: transactionHash,
        },
        method: GET_METHOD,
      },
    );
```

[example transaction](https://bloks.io/transaction/3eae5fe9d49302fcc60957e1164510d1e47c4ed2922f5d859f71ca5607c7fd02)

for example in here, i want to only filter the following actions, not traces, which are
<img width="859" alt="image" src="https://github.com/eosrio/hyperion-history-api/assets/156019107/e537d4b3-99f8-4e9a-a9e5-592c9e87d811">

how to filter correctly? i tried to use creator_action_ordinal but thats not what i was looking for

ps: problem is v2 api, v1 seems working correctly but their json scheme also different

below is another example, where v1 returns all user actions under trx with `creator_action_ordinal` equals to `0`, while v2 returns them mixed, with non zero `creator_action_ordinal`'s
[example transaction](https://bloks.io/transaction/397e3689f359a8271b9cf2320394827f71372df497852f12cc8f0c314bd53aca)

**i need a solid solution for v2 api to get a way to filter only actions created by user like its done in v1, not whole trace**

another question, is there any problem for using v1 api? is it still supported by community, and do you continue to maintain it?

thanks, Dante

**Comment by dev-dantealighieri** [comment]
I'd love your urgent reply 😅 

thank you, Dante

**Comment by igorls** [comment]
For this situation maybe you are looking for an actor filter like: `/v2/history/get_actions?act.authorization.actor=eosio`

V1 is a backport of the old history api provided in nodeos, we do not plan to support it for longer and its not optimized enough, v2 has more flexibility and its focused on the data that is indexed
