### ISSUE TITLE
get transactions of account

### ISSUE THREAD

**Issue by dev-dantealighieri** [eosrio/hyperion-history-api#145]
i want to get transactions of an account instead of actions but your api seems not supporting this, is there a work around for this?

I am currently fetching actions of an account, but this is not what i want, i want to get last N transactions of account with offset

```typescript
const result = await this.indexerRequest(EOS_INDEXER_API.V2.GET_ACTIONS, {
  params: {
    account: address,
    limit: limit,
    skip: offset,
  },
  method: GET_METHOD,
});
```

**Comment by igorls** [comment]
Hyperion was designed to store only actions, but they include the transaction id on each of them. If you want to get only the root actions of each transaction you could use a filter like `/v2/history/get_actions?action_ordinal=1`
