### ISSUE TITLE
querystring.after should match format \"date-time\"

### ISSUE THREAD

**Issue by arnaud9145** [eosrio/Hyperion-History-API#19]
When trying to request the api, it's impossible to use after or before parameters in /v2/history/get_actions. I get a json error : 
```
{
  "statusCode": 400,
  "error": "Bad Request",
  "message": "querystring.after should match format \"date-time\", querystring.before should match format \"date-time\""
}
```

You can reproduce the bug by going to any swagger UI and try to add an after and/or before parameter in ISO8601 format (as requested by the form).
Tried on https://eos.hyperion.eosrio.io/v2/docs/index.html and https://junglehistory.cryptolions.io/v2/docs/index.html with format "2019-10-02T12:00:00" for example.

It doesn't work either with a direct curl : 
`curl -X GET "https://eos.hyperion.eosrio.io/v2/history/get_actions?limit=10&sort=desc&after=2019-10-01T12%3A00%3A00&before=2019-10-02T12%3A00%3A00" -H "accept: application/json"`

Am I doing something wrong ? Maybe the format is not ISO8601 ?

**Comment by igorls** [comment]
You are missing the Z in the end ISO8601 for UTC requires it - "2019-10-02T12:00:00Z"

For example:
https://junglehistory.cryptolions.io/v2/history/get_actions?after=2019-10-02T12%3A00%3A00Z
http://api.eossweden.org/v2/history/get_actions?after=2019-10-02T12%3A00%3A00Z

**Comment by arnaud9145** [comment]
It works thanks ! Just in the @timestamp parameter of an action, it doesn't respect that format. There's no Z. I get "2019-10-04T11:52:50.500" for example when I use get_actions. Maybe it should be a good idea to make it consistent ? Or accept that format without Z in the request ?

**Comment by igorls** [comment]
Good suggestion, unfortunately elasticsearch wont use the Z so it would be better to accept without it

**Comment by igorls** [comment]
Fix Implemented
