### ISSUE TITLE
How to fix this problem while indexer's starting: scaling.max_queue_limit is not defined!

### ISSUE THREAD

**Issue by ashuralyk** [eosrio/hyperion-history-api#38]
vimchain@ubuntu:~/Starteos/Nodeos$ pm2 logs eos-indexer
[TAILING] Tailing last 15 lines for [eos-indexer] process (change the value with --lines option)
/home/vimchain/.pm2/logs/eos-indexer-error.log last 15 lines:
/home/vimchain/.pm2/logs/eos-indexer-out.log last 15 lines:
0|eos-inde | 2020-06-22T01:47:57: [00_master] scaling.max_queue_limit is not defined!

I use "pm2 start" to boot this software, because the "npm run start:indexer" did nothing for me.

**Comment by igorls** [comment]
Please refer to the example chain config file
https://github.com/eosrio/hyperion-history-api/blob/master/chains/example.config.json
yours is probably missing "scaling.max_queue_limit"
