### ISSUE TITLE
I have a problem to use eos-api

### ISSUE THREAD

**Issue by JoYeonJeong** [eosrio/hyperion-history-api#40]
I started 'eos-indexer' and 'eos-api'.

I have a problem to use eos-api.
I can get response about "localhost:7000/v2/state/get_account?account=[myaccountname]"
But, I can't get any response except the api mentioned above.
I can get response => {"query_time_ms":95.029,"cached":false,"lib":0,"total":{"value":0,"relation":"eq"},"actions":[]}

I checked connection from hyperion to nodeos. I can get same chain-id.

please, help me.. 
I can hardly find a solution.

**Comment by tsouza** [comment]
Please, ask your question in the support channel https://t.me/EOSHyperion
