### ISSUE TITLE
/definitions/ecosystem_settings.js references launcher.js, which no longer exist

### ISSUE THREAD

**Issue by littnils** [eosrio/hyperion-history-api#54]
When trying to launch an indexer via
`pm2 start --only chain-indexer --update-env`
the launch fails with the error message that `launcher.js` doesn't exist. Changing it to `launcher.ts` results in a different error  when trying to start the indexer:
`SyntaxError: Cannot use import statement outside a module`.

Also `launcher.ts` does not seem to be a typescript-converted version of `launcher.js`, as the original `launcher.js` has been deleted in this commit https://github.com/eosrio/hyperion-history-api/commit/647b6f70ee5db5b155185b80ef9c9485edb51194  while `launcher.ts` has just been renamed from `indexer.ts`

**Comment by siliconswampio** [comment]
It has happened to me that postinstall script (`package.json`) fails and I had to run the command manually (after `npm install`):

`npm run tsc && npm run fix-permissions`

After that, launcher.js is generated.
