### ISSUE TITLE
the amount shown in the `get_tokens` endpoint is always wrong

### ISSUE THREAD

**Issue by lurk24** [eosrio/hyperion-history-api#58]
Take for example the following account:
https://wax.eosrio.io/v2/state/get_account?account=lurk24dotcom
![image](https://user-images.githubusercontent.com/47430663/121215021-7ca56200-c834-11eb-9cd8-6b0f1e3d31a6.png)

https://wax.eosrio.io/v2/state/get_tokens?account=lurk24dotcom
![image](https://user-images.githubusercontent.com/47430663/121217003-4668e200-c836-11eb-9363-142b0ca53c9b.png)

we see the accurate `account.core_liquid_balance`:
![image](https://user-images.githubusercontent.com/47430663/121215105-90e95f00-c834-11eb-9f97-c45b231a6b5e.png)

and a corresponding value in the `token` array within `get_account` plus the same within the `get_tokens` endpoint:
![image](https://user-images.githubusercontent.com/47430663/121215180-a3fc2f00-c834-11eb-9232-ce3e501cec87.png)

however, the `amount` displayed within the token array and `get_tokens` endpoint is always wrong.

We can see the correct data by looking up the value using `get_table_rows` with this data:
```{"code":"eosio.token","scope":"lurk24dotcom","table":"accounts"}```

or like this: ```wax.rpc.get_currency_balance('eosio.token', 'lurk24dotcom', 'WAX')```

Looking into the source code it seems like this is a cached value and is never really updated... 

It seems like the correct value is obtained on line 42:  `token_data = await fastify.eosjs.rpc.get_currency_balance(data.code, request.query.account, data.symbol)`
https://github.com/eosrio/hyperion-history-api/blob/a5f14071d3062b9ba611165cc40570f09624da3f/api/routes/v2-state/get_tokens/get_tokens.ts#L42

however that line of code is not hit if the token is found in the tokenCache on line 37
https://github.com/eosrio/hyperion-history-api/blob/a5f14071d3062b9ba611165cc40570f09624da3f/api/routes/v2-state/get_tokens/get_tokens.ts#L37

but the `amount` is returned on line 60 
https://github.com/eosrio/hyperion-history-api/blob/a5f14071d3062b9ba611165cc40570f09624da3f/api/routes/v2-state/get_tokens/get_tokens.ts#L60

so it is unclear to me what is the purpose of the `amount` datapoint within this API endpoint if it is always wrong?

**Comment by igorls** [comment]
Closing this is issue since its related to the current state (out-of-sync) of a public API endpoint and not a software issue.
Cheking the data on: https://wax.eosrio.io/v2/health would allow you to see that currently it does have a problem.

**Comment by lurk24** [comment]
you do not think this is a software issue?
please show me at least 1 single API endpoint that is in-sync then....

**Comment by lurk24** [comment]
also, please answer `what is the point of the amount data point if it is always wrong?`
