### ISSUE TITLE
rate limit whitelist including random google cloud IP

### ISSUE THREAD

**Issue by WMcKibbin** [eosrio/Hyperion-History-API#7]
in ./api/api-loader.js

[https://github.com/eosrio/Hyperion-History-API/blob/master/api/api-loader.js#L19](url)

```javascript
fastify.register(require('fastify-rate-limit'), {
    max: 1000,
    whitelist: ["35.230.63.54"],
    timeWindow: '1 minute',
    redis: new Redis()
});
```
Why is this IP here?

**Comment by igorls** [comment]
This wasn't supposed to be included on the repo, this is from bloks.io

**Comment by WMcKibbin** [comment]
Gotcha, thanks for the response.
