### ISSUE TITLE
API auto stop

### ISSUE THREAD

**Issue by appop** [eosrio/hyperion-history-api#77]
2|eos-indexer  | 2022-01-10T19:56:59:
2|eos-indexer  | 2022-01-10T19:56:59:         -------- BLOCK RANGE COMPLETED -------------
2|eos-indexer  | 2022-01-10T19:56:59:         | Range: 225291927 >> 225301416
2|eos-indexer  | 2022-01-10T19:56:59:         | Total time: 55 seconds
2|eos-indexer  | 2022-01-10T19:56:59:         | Blocks: 9489
2|eos-indexer  | 2022-01-10T19:56:59:         | Actions: 174539
2|eos-indexer  | 2022-01-10T19:56:59:         | Deltas: 340605
2|eos-indexer  | 2022-01-10T19:56:59:         | ABIs: 1
2|eos-indexer  | 2022-01-10T19:56:59:         --------------------------------------------

The eos-indexer auto stop after completed the syncing, even the block update,
It will auto stop after 300s.

**Comment by igorls** [comment]
please reopen if relevant on the latest version and include more information on the issue
